// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindMap.Api.Infrastructure.Data;

#nullable disable

namespace MindMap.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817122307_AddMindMapShare")]
    partial class AddMindMapShare
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MindMap.Api.Domain.Entities.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId", "ParentId", "SortOrder");

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.MindMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CoverImage")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)");

                    b.Property<int>("DefaultLayout")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastEditedAt")
                        .HasColumnType("datetime(3)");

                    b.Property<int>("NodeCount")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RootNodeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Theme")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("RootNodeId")
                        .IsUnique();

                    b.HasIndex("IsPublic", "LastEditedAt");

                    b.HasIndex("OwnerId", "UpdatedAt");

                    b.ToTable("mindmaps", (string)null);
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.MindMapShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessCount")
                        .HasColumnType("int");

                    b.Property<bool>("AllowCopy")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(3)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime(3)");

                    b.Property<int?>("MaxAccessCount")
                        .HasColumnType("int");

                    b.Property<Guid>("MindMapId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Password")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ShareToken")
                        .IsUnique();

                    b.HasIndex("MindMapId", "CreatedAt");

                    b.ToTable("mindmap_shares", (string)null);
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.MindMapVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MindMapId")
                        .HasColumnType("char(36)");

                    b.Property<int>("NodeCount")
                        .HasColumnType("int");

                    b.Property<string>("NodeSnapshotJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MindMapId", "VersionNumber")
                        .IsUnique()
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_mindmap_versions_mindmap_version");

                    b.ToTable("mindmap_versions", (string)null);
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("BorderColor")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Content")
                        .HasMaxLength(16384)
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)");

                    b.Property<string>("EdgeColor")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int?>("EdgeStyle")
                        .HasColumnType("int");

                    b.Property<string>("ExtraData")
                        .HasMaxLength(32768)
                        .HasColumnType("longtext");

                    b.Property<string>("FontFamily")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("FontSize")
                        .HasColumnType("int");

                    b.Property<double?>("Height")
                        .HasPrecision(8, 2)
                        .HasColumnType("double");

                    b.Property<string>("Icon")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsCollapsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MindMapId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Note")
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Shape")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)");

                    b.Property<double?>("Width")
                        .HasPrecision(8, 2)
                        .HasColumnType("double");

                    b.Property<double?>("X")
                        .HasPrecision(12, 4)
                        .HasColumnType("double");

                    b.Property<double?>("Y")
                        .HasPrecision(12, 4)
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("MindMapId");

                    b.HasIndex("ParentId");

                    b.HasIndex("MindMapId", "ParentId", "SortOrder");

                    b.ToTable("nodes", (string)null);
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(3)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(88)
                        .HasColumnType("varchar(88)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(3)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("varchar(88)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Avatar")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(3)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("mindmap_tags", b =>
                {
                    b.Property<Guid>("MindMapId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("char(36)");

                    b.HasKey("MindMapId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("mindmap_tags");
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.Folder", b =>
                {
                    b.HasOne("MindMap.Api.Domain.Entities.Folder", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MindMap.Api.Domain.Entities.User", "User")
                        .WithMany("Folders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.MindMap", b =>
                {
                    b.HasOne("MindMap.Api.Domain.Entities.Folder", "Folder")
                        .WithMany("MindMaps")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MindMap.Api.Domain.Entities.User", "Owner")
                        .WithMany("MindMaps")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindMap.Api.Domain.Entities.Node", "RootNode")
                        .WithOne()
                        .HasForeignKey("MindMap.Api.Domain.Entities.MindMap", "RootNodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Folder");

                    b.Navigation("Owner");

                    b.Navigation("RootNode");
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.MindMapShare", b =>
                {
                    b.HasOne("MindMap.Api.Domain.Entities.MindMap", "MindMap")
                        .WithMany()
                        .HasForeignKey("MindMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MindMap");
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.MindMapVersion", b =>
                {
                    b.HasOne("MindMap.Api.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MindMap.Api.Domain.Entities.MindMap", "MindMap")
                        .WithMany()
                        .HasForeignKey("MindMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("MindMap");
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.Node", b =>
                {
                    b.HasOne("MindMap.Api.Domain.Entities.MindMap", "MindMap")
                        .WithMany("Nodes")
                        .HasForeignKey("MindMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindMap.Api.Domain.Entities.Node", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MindMap");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MindMap.Api.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.Tag", b =>
                {
                    b.HasOne("MindMap.Api.Domain.Entities.User", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("mindmap_tags", b =>
                {
                    b.HasOne("MindMap.Api.Domain.Entities.MindMap", null)
                        .WithMany()
                        .HasForeignKey("MindMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindMap.Api.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.Folder", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MindMaps");
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.MindMap", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.Node", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("MindMap.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Folders");

                    b.Navigation("MindMaps");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
